# Generated by Django 3.2.8 on 2023-05-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libro',
            new_name='libros',
        ),
    ]
