# Generated by Django 3.2.8 on 2023-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_libro_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='description',
            new_name='descripcion',
        ),
    ]
